config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :groups, only: %i[index new create] do
    resources :operations, only: %i[index]
  end
  resources :operations, only: %i[new create]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    return unless user.present?

    can :manage, Group, author_id: user.id
    can :manage, Operation, author_id: user.id
  end
  # The first argument to `can` is the action you are giving the user
  # permission to do.
  # If you pass :manage it will apply to every action. Other common actions
  # here are :read, :create, :update and :destroy.
  #
  # The second argument is the resource the user can perform the action on.
  # If you pass :all it will apply to every resource. Otherwise pass a Ruby
  # class of the resource.
  #
  # The third argument is an optional hash of conditions to further filter the
  # objects.
  # For example, here the user can only update published articles.
  #
  #   can :update, Article, published: true
  #
  # See the wiki for details:
  # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :operations

  validates :name, presence: true, length: { in: 1..100 }
  validates :icon, presence: true, length: { in: 1..300 }
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :groups

  validates :name, presence: true, length: { in: 1..100 }
  validates :amount, numericality: { greater_than_or_equal_to: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups
  has_many :operations

  validates :name, presence: true, length: { in: 1..100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from 'CanCan::AccessDenied' do |_exception|
    redirect_to root_path, alert: 'You are not authorized to access that page.'
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    groups_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource

  def index
    @groups = Group.where(author_id: current_user.id).order(created_at: :desc)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to groups_path, notice: 'Successfully created a group.'
    else
      flash[:alert] = 'Failed to create a group.'
      render :new
    end
  end

  private

  def group_params
    gp = params.require(:group).permit(:name, :icon)
    gp[:author_id] = current_user.id
    gp
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to groups_path if current_user
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  load_and_authorize_resource

  def index
    @group = Group.find_by(id: params[:group_id])
    @operations = helpers.find_operations
  end

  def new
    @operation = Operation.new
  end

  def create
    @operation = Operation.new(operation_params)

    helpers.create_groups_operations(@operation, params[:group][:group_id])

    if @operation.save
      redirect_to groups_path, notice: 'Successfully created an operation.'
    else
      flash[:alert] = 'Failed to create an operation.'
      render :new
    end
  end

  private

  def operation_params
    op = params.require(:operation).permit(:name, :amount)
    op[:author_id] = current_user.id
    op
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_amount(group)
    total_amount = 0

    group.operations.each do |operation|
      total_amount += operation.amount
    end
    total_amount
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
  def find_operations
    if params[:group_id]
      Group.find(params[:group_id]).operations
    else
      Operation.all
    end
  end

  def create_groups_operations(operation, array)
    i = 1

    while i < array.length
      group = Group.find_by(id: array[i])
      operation.groups << group
      i += 1
    end
  end
end

app/views/groups/index.html.erb
<header class="bg-primary p-2 d-flex justify-content-around align-items-center">

    <div>
      <h1 class="text-center"><i class="bi bi-wallet-fill fs-1"></i>  All Groups </h1>
    </div>
    <div>
      <li class="nav-item align-items-center">
        <%= link_to "Sign Out", destroy_user_session_path, method: :get, class: 'nav-link btn btn-danger text-white' %>
      </li>
    </div>
  </header>
  
  <section class="container mt-3">
    <% if @groups.empty? %>
      <div class="padding border">
        <h3 class="text-center mt-5">No groups yet.</h3>
      </div>
    <% else %>
    <% @groups.each do |group| %>
      <div class="d-flex border border-1 p-4 shadow-sm align-items-center mt-3 me-auto group_card justify-content: space-between">
        <div>
          <img src=<%= group.icon %> alt=<%= group.name %> class="img-thumbnail" style="width: 30%">
        </div>
        <div class="">
          <div>
            <h3 class="link fs-4"><%= link_to group.name, group_operations_path(group_id: group.id) %></h3>
          </div>
          <p>
            <%= group.created_at.strftime("%d %b %Y") %>
          </p>
        </div>
  
        <div class="price">
          <p class="fs-4 fw-bolder text-secondary">$<%= group_amount(group) %></p>
        </div>      
      </div>
    <% end %>
    <% end %>
    <div class="margin">
      <%= link_to "Add group", new_group_path, class: "fixed-bottom d-flex justify-content-center w-100 m-auto btn-lg p-4 mt-4 btn btn-success" %>
    </div>
  </section>

app/views/groups/new.html.erb
<header class="bg-primary p-2">
    <h1 class="position-absolute">
      <%= link_to root_path do %>
        <i class="bi bi-caret-left-fill m-2 fs-4 rounded p-2 text-dark"></i>
      <% end %>
    </h1>
    <h1 class="text-center text-light"> Add Group </h1>
  </header>
  
  <div>
    <%= render "shared/group_form" %>
  </div>

app/views/home/index.html.erb
<header class="headercontainer">
    <h1><i class="bi bi-wallet-fill"></i> Budget App</h1>
  </header>
  <section class="information container border">
    <div class="container margin-b">
      <h2 class="heading">How it works</h2>
      <p>
        Easily manage your budget. Have a list of transactions associated with a category, so that you can see how much money you spent and on what.
      </p>
    </div>
  
    <div class="container margin-b">
      <h2 class="heading">Join now</h2>
      <p>
        If you haven't already, <%= link_to "sign up now", new_user_registration_path, class: "link" %> or if you already have an account, <%= link_to "sign in", new_user_session_path, class: "link" %>.
      </p>
    </div>
  </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/operations/index.html.erb
<header class="bg-primary p-2 d-flex justify-content-around align-items-center">
    <div>
      <%= link_to groups_path do %>
        <i class="bi bi-caret-left-fill m-2 fs-4 rounded p-2 text-dark"></i>
      <% end %>  </div>
    <div>
      <h1 class="text-center fs-2 text-light"> Operations for <%= @group.name %> </h1>
    </div>
    <div>
      <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path, method: :get, class: 'nav-link btn btn-danger text-white' %>
      </li>
  </header>
  
  <div class="bg-secondary text-light">
    <p  class="text-center p-2">Money spent: $<%= group_amount(@group) %></p>
  </div>
  
  <section class="container">
  
    <% if @operations.empty? %>
      <div class="mt-5">
        <h3 class="text-center">No operations yet.</h3>
      </div>
    <% else %>
      <% @operations.each do |operation| %>
        <div class="p-4 border border-1 shadow-sm m-4 d-flex justify-content-between">
          <h3 class="m-2"><%= operation.name %></h3>
          <p class="m-2 fs-4 fw-bolder text-secondary">$<%= operation.amount %></p>
        </div>
      <% end %>
    <% end %>
    <div class="margin">
      <%= link_to "Add operation", new_operation_path, class: "fixed-bottom d-flex justify-content-center w-100 m-auto btn-lg p-4 mt-4 btn btn-success" %>
    </div>
  </section>

app/views/operations/new.html.erb
<header class="bg-primary p-2 d-flex justify-content-around align-items-center">
    <div>
      <%= link_to groups_path do %>
        <i class="bi bi-caret-left-fill m-2 fs-4 rounded p-2 text-dark"></i>
      <% end %>  
    </div>
    <div>
      <h1 class="text-center fs-2 text-light"> Add Operations </h1>
    </div>
    <div>
      <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path, method: :get, class: 'nav-link btn btn-danger text-white' %>
      </li>
  </header>
  
  <div class="container">
    <%= render "shared/operation_form" %>
  </div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="notice-container">
    <p class="notice"><%= notice %></p>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert-container">
    <p class="alert"><%= alert %></p>
  </div>
<% end %>

app/views/shared/_grouo_form.html.erb
<div class="mt-5">
    <%= form_with model: @group, data: { turbo: false }, class: "container form margin-y border-y" do |form| %>

    <div class="form-group mt-2">
        <%= form.label :name, class: "form-label fs-5" %>
        <%= form.text_field :name, autofocus: true, class: "form-control p-2", required: true %>
    </div>

    <div class="form-group mt-2">
        <%= form.label :icon, class: "form-label fs-5" %>
        <%= form.text_field :icon, class: "form-control p-2", required: true %>
    </div>

    <%= form.submit "Save", class: "btn btn-success mt-2" %>
    <% end %>
</div>

app/views/shared/_group_form.html.erb
<div class="mt-5">
    <%= form_with model: @group, data: { turbo: false }, class: "container form margin-y border-y" do |form| %>

    <div class="form-group mt-2">
        <%= form.label :name, class: "form-label fs-5" %>
        <%= form.text_field :name, autofocus: true, class: "form-control p-2", required: true %>
    </div>

    <div class="form-group mt-2">
        <%= form.label :icon, class: "form-label fs-5" %>
        <%= form.text_field :icon, class: "form-control p-2", required: true %>
    </div>

    <%= form.submit "Save", class: "btn btn-success mt-2" %>
    <% end %>
</div>

app/views/shared/_operation_form.html.erb
<div class="container d-flex flex-column align-items-center mt-4">
    <%= form_with model: @operation, data: { turbo: false }, class: "" do |form| %>

    <div class="form-group mt-2">
        <%= form.label :name, class: "form-label fs-5" %>
        <%= form.text_field :name, autofocus: true, class: "form-control", required: true %>
    </div>

    <div class="form-group mt-2">
        <%= form.label :amount, class: "form-label fs-5" %>
        <%= form.number_field :amount, class: "form-control", required: true %>
    </div>

    <div class="form-group mt-2">
        <%= form.label :group, class: "form-label fs-5" %>
        <%= select("group", "group_id", Group.all.collect { |g| [ g.name, g.id ] }, { include_blank: false }, multiple: true, size: 3, class: "form-control", required: true) %>
    </div>

    <%= form.submit "Save", class: "btn btn-success mt-4 w-100 text-center" %>
    <% end %>
</div>